---
Name: silverstripe-frontend-forms
---
Syntro\SilverstripeFrontendForms\Forms\CheckboxField:
  default_classes: ['form-check-input']
  default_holder_classes: ['form-check']

Syntro\SilverstripeFrontendForms\Forms\TextareaField:
  default_classes: ['form-control']
