---
Name: silverstripe-bootstrap-forms
---
Syntro\SilverstripeBootstrapForms\Forms\CheckboxField:
  default_classes: ['form-check-input']
  default_holder_classes: ['form-check']

Syntro\SilverstripeBootstrapForms\Forms\DropdownField:
  default_classes: ['form-select']

Syntro\SilverstripeBootstrapForms\Forms\EmailField:
  default_classes: ['form-control']

Syntro\SilverstripeBootstrapForms\Forms\FieldGroup:
  default_classes: ['row']

Syntro\SilverstripeBootstrapForms\Forms\OptionsetField:
  default_classes: ['form-check']

Syntro\SilverstripeBootstrapForms\Forms\TextareaField:
  default_classes: ['form-control']

Syntro\SilverstripeBootstrapForms\Forms\TextField:
  default_classes: ['form-control']

Syntro\SilverstripeBootstrapForms\Forms\PhoneField:
  default_classes: ['form-control']

Syntro\SilverstripeBootstrapForms\Forms\ReadonlyField:
  default_classes: ['form-control']
