name: 🎭 Tests
on:
  - push
env:
  DB: MYSQL
  PDO: 1
  SS_ENVIRONMENT_TYPE: "dev"
  RECIPE_CMS_VERSION: 4.x-dev
jobs:
  silverstripe-module:
    name: 🧰 Silverstripe Module Testsuite
    uses: syntro-opensource/workflows/.github/workflows/silverstripe-module.yml@master
    with:
      phpunit: true
      phpstan: true
      phpcs: true
